<?php
    echo "<footer>
            <h2>Our Team</h2>
            <ul class='footlist'>
                <li><a href='mailto:103515617@student.swin.edu.au'>Khoa (103515617)</a></li>
                <li><a href='mailto:103510447@student.swin.edu.au'>Singh (103510447)</a></li>
                <li><a href='mailto:103178955@student.swin.edu.au'>Minh (103178955)</a></li>
                <li><a href='mailto:102673815@student.swin.edu.au'>Bradley (102673815)</a></li>
                <li><a href='mailto:103982376@student.swin.edu.au'>Andrew (103982376)</a></li>
            </ul>
            <br/>
            <div class='footer-logo'>
                <div class='icon'>
                    <div class='elip' id = 'feli1'></div>
                    <div class='elip' id = 'feli2'></div>
                    <div class='elip' id = 'feli3'></div>
                    <div class='ball'></div>
                </div>
                <div class='flogo-text'>
                <a href='index.php'>React<span class='blue'>JS</span></a>
                <p class='des'>A COS10026 Project<br/>by <span class='blue'>React Lions</span></p></div>
            </div>
        </footer>";
?>