<!--
PHP file for a COS10026 Project by React Lions
Author: 
Duy Khoa Pham (103515617)
Gurmehar Singh (103510447)
Anh Minh Nguyen (103178955)
Bradley Bowering (102673815)
Andrew Moutsos(103982376)
Purpose: logout enhancement
last modified: 27.05.2022 
 -->
<?php
    echo "<header>
        <div class='logo'>
            <div class='icon'>
                <div class='elip' id = 'eli1'></div>
                <div class='elip' id = 'eli2'></div>
                <div class='elip' id = 'eli3'></div>
                <div class='ball'></div>
            </div>
            <h1><a href='index.php'>React<span class='blue'>JS</span></a>
            </h1>
        </div>";
?>