<?php
    echo "<header>
        <div class='logo'>
            <div class='icon'>
                <div class='elip' id = 'eli1'></div>
                <div class='elip' id = 'eli2'></div>
                <div class='elip' id = 'eli3'></div>
                <div class='ball'></div>
            </div>
            <h1><a href='index.php'>React<span class='blue'>JS</span></a>
            </h1>
        </div>";
?>